version: '3'
services:
  server:
    command: /bin/bash ./bin/prod.sh
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: hsserver
    env_file: .env
    volumes:
      - ./server:/app
      - ./logs/gunicorn:/var/log/gunicorn
      - ./frontend/dist:/app/app/static/dist
    expose:
      - "8000"
    depends_on:
      - db
    ports:
      - "8443:8443"
    restart: always
  db:
    image: postgres:11.0
    container_name: hmsdb
    restart: always
    expose:
      - "5432"
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nginx:
    container_name: hmsnginx
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "8888:80"
      - "8889:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./server:/app
